[book]
title = "Scaphandre documentation"
description = "Extensible and lightweight monitoring agent for energy consumption metrics"
authors = ["Benoit Petit"]
language = "en"
src = "docs_src"

[build]
build-dir = "../scaphandre-documentation/docs"
extra-watch-dirs = ["po"]

[rust]
edition = "2018"

# https://github.com/google/mdbook-i18n-helpers/blob/main/i18n-helpers/USAGE.md#building-a-translated-book
[preprocessor.gettext]
after = ["links"]

[output.html]
mathjax-support = false
git-repository-url = "https://github.com/hubblo-org/scaphandre"
site-url = "/docs/"

[output.html.playground]
editable = true
line-numbers = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2
